-- Multi-shop (go-public B2). Additive: every tenant table gets shopId (default 'default' = Top Gun); per-shop numbers.
PRAGMA foreign_keys=OFF;
ALTER TABLE "Employee" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Employee_shopId_idx" ON "Employee"("shopId");
ALTER TABLE "Boss" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Boss_shopId_idx" ON "Boss"("shopId");
ALTER TABLE "Customer" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Customer_shopId_idx" ON "Customer"("shopId");
ALTER TABLE "Invoice" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Invoice_shopId_idx" ON "Invoice"("shopId");
DROP INDEX "Invoice_number_key";
CREATE UNIQUE INDEX "Invoice_shopId_number_key" ON "Invoice"("shopId", "number");
ALTER TABLE "Estimate" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Estimate_shopId_idx" ON "Estimate"("shopId");
DROP INDEX "Estimate_number_key";
CREATE UNIQUE INDEX "Estimate_shopId_number_key" ON "Estimate"("shopId", "number");
ALTER TABLE "DeliveryEvent" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "DeliveryEvent_shopId_idx" ON "DeliveryEvent"("shopId");
ALTER TABLE "DocLine" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "DocLine_shopId_idx" ON "DocLine"("shopId");
ALTER TABLE "Job" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Job_shopId_idx" ON "Job"("shopId");
DROP INDEX "Job_code_key";
CREATE UNIQUE INDEX "Job_shopId_code_key" ON "Job"("shopId", "code");
ALTER TABLE "JobPhoto" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "JobPhoto_shopId_idx" ON "JobPhoto"("shopId");
ALTER TABLE "Receipt" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Receipt_shopId_idx" ON "Receipt"("shopId");
ALTER TABLE "ServiceCode" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "ServiceCode_shopId_idx" ON "ServiceCode"("shopId");
DROP INDEX "ServiceCode_code_key";
CREATE UNIQUE INDEX "ServiceCode_shopId_code_key" ON "ServiceCode"("shopId", "code");
ALTER TABLE "TimeEntry" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "TimeEntry_shopId_idx" ON "TimeEntry"("shopId");
ALTER TABLE "PayPeriod" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "PayPeriod_shopId_idx" ON "PayPeriod"("shopId");
ALTER TABLE "PayAdjustment" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "PayAdjustment_shopId_idx" ON "PayAdjustment"("shopId");
ALTER TABLE "JobCost" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "JobCost_shopId_idx" ON "JobCost"("shopId");
ALTER TABLE "PriceMemory" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "PriceMemory_shopId_idx" ON "PriceMemory"("shopId");
ALTER TABLE "AuditLog" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "AuditLog_shopId_idx" ON "AuditLog"("shopId");
ALTER TABLE "Alert" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Alert_shopId_idx" ON "Alert"("shopId");
ALTER TABLE "Account" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "Account_shopId_idx" ON "Account"("shopId");
ALTER TABLE "CrewPing" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "CrewPing_shopId_idx" ON "CrewPing"("shopId");
ALTER TABLE "PushDevice" ADD COLUMN "shopId" TEXT NOT NULL DEFAULT 'default';
CREATE INDEX "PushDevice_shopId_idx" ON "PushDevice"("shopId");
PRAGMA foreign_keys=ON;
