// Writes prisma/schema.postgres.prisma from prisma/schema.prisma with the provider switched to PostgreSQL.
// prisma/schema.prisma stays the one source of truth (SQLite for local dev); the Postgres copy is generated,
// never hand-edited, and gitignored, so a column another worker adds locally reaches Vercel automatically.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const POSTGRES_SCHEMA = join(root, "prisma", "schema.postgres.prisma");

export function writePostgresSchema() {
  const src = readFileSync(join(root, "prisma", "schema.prisma"), "utf8");
  const swapped = src.replace(/(datasource\s+db\s*\{[^}]*?provider\s*=\s*)"sqlite"/, '$1"postgresql"');
  if (swapped === src) throw new Error('prisma/schema.prisma: could not find provider = "sqlite" in datasource db');
  writeFileSync(
    POSTGRES_SCHEMA,
    "// GENERATED by scripts/postgres-schema.mjs from prisma/schema.prisma. Do not edit.\n" + swapped
  );
  return POSTGRES_SCHEMA;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  console.log(writePostgresSchema());
}
